plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.5'
    id 'com.google.protobuf' version '0.9.6'
    id 'io.freefair.lombok' version '9.2.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.interview'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.projectreactor.netty:reactor-netty-core'
    implementation 'com.google.protobuf:protobuf-java:4.34.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.mockito:mockito-core:5.11.0'
}

test {
    useJUnitPlatform()
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.34.0"
    }
}